/*
PROBLEM: Find the Difference
==============================
Given two strings s and t where t is generated by shuffling s and 
adding one more letter, find the letter that was added.

APPROACH:
- XOR all characters in both strings
- Duplicate characters cancel out
- The added character remains

PATTERN: XOR for Character Comparison

INPUT/OUTPUT:
Input: s = "abcd", t = "abcde"
Output: 'e'
Explanation: 'e' is added to t

Input: s = "", t = "y"
Output: 'y'

TIME COMPLEXITY: O(n)
SPACE COMPLEXITY: O(1)
*/

#include <iostream>
#include <string>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        char result = 0;
        
        // XOR all characters in s
        for (char c : s) {
            result ^= c;
        }
        
        // XOR all characters in t
        for (char c : t) {
            result ^= c;
        }
        
        // Result contains the added character
        return result;
    }
    
    // Alternative: Using sum difference
    char findTheDifferenceSumMethod(string s, string t) {
        int sum = 0;
        for (char c : t) sum += c;
        for (char c : s) sum -= c;
        return (char)sum;
    }
};

int main() {
    Solution sol;
    
    // Test Case 1
    string s1 = "abcd", t1 = "abcde";
    cout << "Input: s = \"" << s1 << "\", t = \"" << t1 << "\"" << endl;
    cout << "Output: '" << sol.findTheDifference(s1, t1) << "'" << endl;
    cout << "Explanation: 'e' was added to t" << endl << endl;
    
    // Test Case 2
    string s2 = "", t2 = "y";
    cout << "Input: s = \"" << s2 << "\", t = \"" << t2 << "\"" << endl;
    cout << "Output: '" << sol.findTheDifference(s2, t2) << "'" << endl;
    cout << "Explanation: Only character in t" << endl << endl;
    
    // Test Case 3
    string s3 = "a", t3 = "aa";
    cout << "Input: s = \"" << s3 << "\", t = \"" << t3 << "\"" << endl;
    cout << "Output: '" << sol.findTheDifference(s3, t3) << "'" << endl;
    cout << "Explanation: Extra 'a' was added" << endl;
    
    return 0;
}
