"""
PROBLEM: Find the Difference
==============================
Given two strings s and t where t is generated by shuffling s and 
adding one more letter, find the letter that was added.

APPROACH:
- XOR all characters in both strings
- Duplicate characters cancel out
- The added character remains

PATTERN: XOR for Character Comparison

INPUT/OUTPUT:
Input: s = "abcd", t = "abcde"
Output: 'e'
Explanation: 'e' is added to t

Input: s = "", t = "y"
Output: 'y'

TIME COMPLEXITY: O(n)
SPACE COMPLEXITY: O(1)
"""

from typing import List, Optional

class Solution:
    def findTheDifference(self, s, t):
        char result = 0
        # XOR all characters in s
        for c in s:
        result ^= c
        # XOR all characters in t
        for c in t:
        result ^= c
        # Result contains the added character
        return result


if __name__ == "__main__":
    sol = Solution()
    s1 = "abcd", t1 = "abcde"
    print(f"Input: s = \{s1}")
    print(f"Output: '{sol.findTheDifference(s1,}")
    print(f"Explanation: 'e' was added to t")
    s2 = "", t2 = "y"
    print(f"Input: s = \{s2}")
    print(f"Output: '{sol.findTheDifference(s2,}")
    print(f"Explanation: Only character in t")
    s3 = "a", t3 = "aa"
    print(f"Input: s = \{s3}")
    print(f"Output: '{sol.findTheDifference(s3,}")
    print(f"Explanation: Extra 'a' was added")
